version: "3"

services:
    zap:
        image: owasp/zap2docker-stable
        ports:
            - 8888:8080
            - 8099:8090
        command:  zap-webswing.sh
        networks:
            - odoodocker_default
networks:
    odoodocker_default:
        external: true




